# .github/workflows/ci.yml
name: CI
on: [push, pull_request]
jobs:
  call-reusable:
    uses: MBTQ-dev/mbtq.dev/.github/workflows/reusable-ci-models.yml@main
    with:
      changed_paths: ${{ join(github.event.commits.*.modified, ' ') }}
      run_type: incremental
    secrets:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      GCS_MODEL_BUCKET: ${{ secrets.GCS_MODEL_BUCKET }}
