name: Swagger UI Deployment

on:
  push:
    branches:
      - main
    paths:
      - "openapi/**"
      - ".github/workflows/swagger-ui.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Swagger UI
        run: |
          npm install swagger-ui-dist

      - name: Prepare Swagger UI bundle
        run: |
          mkdir -p public/swagger
          cp -r node_modules/swagger-ui-dist/* public/swagger/
          cp openapi/openapi.yaml public/swagger/openapi.yaml
          sed -i 's|https://petstore.swagger.io/v2/swagger.json|./openapi.yaml|g' public/swagger/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/swagger

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
